# Generated by Django 6.0.6 on 2026-07-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total',
            new_name='total_amount',
        ),
    ]
